'use client'

import { TriageResult } from '@/data/scenarios'

interface PrintableComplaintProps {
  result: TriageResult
  language: 'en' | 'hi'
}

export default function PrintableComplaint({ result, language }: PrintableComplaintProps) {
  const hi = language === 'hi'
  const draft = hi ? result.complaintDraftHi : result.complaintDraft

  return (
    <div className="print-only bg-white p-8 font-mono text-sm text-black">
      <div className="text-center mb-6">
        <h1 className="text-lg font-bold">
          {hi ? 'साइबर अपराध शिकायत / Cyber Crime Complaint' : 'Cyber Crime Complaint'}
        </h1>
        <p className="text-xs text-gray-500">Incident ID: {result.incidentId}</p>
        <p className="text-xs text-gray-500">
          Generated by Samarthan AI Triage | {new Date().toLocaleDateString('en-IN')}
        </p>
        <hr className="mt-3" />
      </div>
      <pre className="whitespace-pre-wrap leading-relaxed text-xs">
        {draft}
      </pre>
      <div className="mt-8 border-t pt-4 text-xs text-gray-400">
        <p>* This is a synthetic AI-generated draft for reference. Verify all details before filing.</p>
        <p>* National Cybercrime Helpline: 1930 | Portal: cybercrime.gov.in</p>
      </div>
    </div>
  )
}
